### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by Michael33X** [andydunkel/hosteurope_letsencrypt#1]
Hello, first of all thank you for the great script. Now I can automate the creation of the certificates. A great help.

In the past I created my certificates manually with:
[https://github.com/sverrirs/GetHttpsForFree-UI](https://github.com/sverrirs/GetHttpsForFree-UI)
[https://gethttpsforfree.com/](https://gethttpsforfree.com)
This works well, but is time consuming.

About your script "hosteurope_letsencrypt" I have two questions respectively suggestions:

1. When the certificates are generated manually, an e-mail address is sent to Let's Encrypt, e.g. webwaster@XXX. To this address Let's Encrypt sends reminders just before the certificates expire. Does this work the same way with your script?
2. I would like to avoid for security reasons sending the certificates by email. After all, the generated keys are already on the web server, which I can access via ftp. So what sense does it make to send the certificates via email?
Is it enough to remove the function "function sendCertificate($myemail)" in the file "main.php" to prevent sending by e-mail?

**Comment by andydunkel** [comment]
Hi, yes your email is registered with LetsEncrypt, so you would get an email about the expiration. The mail is send using phpMailer, is just uses your servers "mail" funktion from PHP. phpMailer can be configured for SMTP as well, but thats up to you in the code.

If you do not want to send the certs via email, just comment the sendCertificate($argv[1]); out in line 181 of the script. The certificates will also be placed in the same folder. You can then do whatever you want with them, download via FTP etc.

Hope that help.
Andy

**Comment by Michael33X** [comment]
Thank You very much.
